name: Build Docker Image

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      # Ignore changes to README.md and docker-compose.yml
      - "README.md"
      - "docker-compose.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Github Short SHA
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags:
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          annotations: |
            org.opencontainers.image.revision=${{ github.sha }}
